swagger: "2.0"
info:
  description: This is the swagger file that goes with the API Server
  version: "1.0.0"
  title: USERSTORIES API Server
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /stories:
    get:
      operationId: stories.read_all
      tags:
        - stories
      summary: Read the entire list of stories
      description: Read the list of stories
      parameters:
        - name: limit
          in: query
          type: integer
          description: Number of stories to return
          required: false
      responses:
        200:
          description: Successfully read stories list operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: number
                title:
                  type: string
                author:
                  type: string
                createdDate:
                  type: string
                summary:
                  type: string
                tags:
                  type: string
    post:
      operationId: stories.create
      tags:
        - stories
      summary: Create a story and add it to the DB
      description: Create a new story in the Database
      parameters:
        - name: story
          in: body
          description: Story to add to DB
          required: True
          schema:
            type: object
            properties:
              title:
                type: string
              author:
                type: string
              summary:
                type: string
              tags:
                type: string
      responses:
        200:
          description: Successfully created stories list operation
          schema:
            type: object
            properties:
              id:
                type: number
              title:
                type: string
              author:
                type: string
              createdDate:
                type: string
              summary:
                type: string
              tags:
                type: string

  # /storytext: